Repository Pieces-of-Life/POL_Server, pull requests merged in 2023-01, with the labels that each got.

#3 [POL-31] FEAT : Add result form
  src/main/java/com/umc/pol/Global/Response/CommonResponse.java
  src/main/java/com/umc/pol/Global/Response/ListResponse.java
  src/main/java/com/umc/pol/Global/Response/ResponseService.java
  src/main/java/com/umc/pol/Global/Response/SingleResponse.java
  src/main/java/com/umc/pol/User/User.java
  src/main/java/com/umc/pol/User/UserController.java
  src/main/java/com/umc/pol/User/UserRepository.java
  src/main/java/com/umc/pol/User/UserService.java
  src/main/java/com/umc/pol/User/dto/UserDto.java
Labels: 💡feature

#5 [POL-34] FEAT : Arrange project settings
  .github/workflows/main.yml
  .gitignore
  build.gradle
  src/main/java/com/umc/pol/global/config/OpenApiConfig.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 🧹chore

#7 [POL-34] FIX : FIX CI/CD
  .github/workflows/main.yml
  build.gradle
  src/main/java/com/umc/pol/global/config/JasyptConfig.java
  src/main/resources/application.yml
Labels: 🛠️fix
